name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Install Playwright and dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests in Chrome 
        run: npx playwright test --project="Google Chrome" --reporter=html

      - name: Upload Playwright report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
